### ISSUE TITLE
Connection lock locks up server

### ISSUE THREAD

**Issue by RenolY2** [SopaXorzTaker/classic-server#7]
After a successful connection, it is possible that the connection lock isn't released properly, causing new connection attempts to freeze indefinitely. More specifically, the connection thread that accepts new connections blocks here: https://github.com/SopaXorzTaker/classic-server/blob/6f900a8273721bd34ad60ccc60e41c32788fa3f1/classicserver/server.py#L148

As the connection lock is used in other places too, this can potentially cause the entire server to lock up. Thus this issue is likely related to issue #6.

**Comment by SopaXorzTaker** [comment]
Seems to be fixed now.
